### ISSUE TITLE
Include `avoid_hardcoded_japanese` warnings only in Widget

### ISSUE THREAD

**Issue by yuukiw00w** [altive/altive_lints#66]
Japanese string literals that are not displayed in widgets are likely not eligible for multilingual support.
For example, Analytics event string literals are currently being falsely detected, so it would be a hassle to specify all of these as targets to be ignored.
Since the only string literals that require multilingual support are those drawn in widgets, it would be great if you could exclude strings that are not included in widgets.

**Comment by riscait** [comment]
It seems undesirable to limit it to widgets, since strings may be set not only for widgets, but also for Enums, certain classes, etc.

I hope that you will use `ignore` for files. to set the wording.
```dart
// ignore_for_file
```

**Comment by yuukiw00w** [comment]
I think there are several projects that manage analytics screen names by linking them to Screen widgets, or use Japanese for assert messages. At least in my project, I do this, and if I were to specify ignore for all screen name definitions and asserts, I would definitely end up with hundreds of lines of ignores, which I feel is a futile task.
Of course, I understand that it’s structurally difficult for the Lint to determine whether a string is displayed in a Widget, so this issue is more of a request for support if possible. If the decision is made not to address it, I will respect that judgment.

**Comment by riscait** [comment]
Are you using `ignore_for_file`? If you are using it, I think it's unlikely to be hundreds of lines.

If you define Japanese for Analytics in the same file as the Widget, `ignore` will be troublesome, so it is recommended to prepare a file for Analytics and define Japanese there.

---

 It seems like a good idea to modify the Japanese in the assert to exclude the warning!

**Comment by yuukiw00w** [comment]
That seems to be a different management approach, so in my project, we’ll likely decide not to use this Lint rule. Thank you for checking.
