### ISSUE TITLE
`avoid_hardcoded_color` warnings false detection in ColorScheme definition

### ISSUE THREAD

**Issue by yuukiw00w** [altive/altive_lints#67]
**Describe the bug**
I get a warning `avoid_hardcoded_color` when defining ColorScheme

**To Reproduce**
```dart
ColorScheme get _darkColorScheme => const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromRGBO(xxx, xxx, xxx, x), // `avoid_hardcoded_color` warnings here
);
```

**Expected behavior**
ColorScheme definition has not warnings

**Comment by riscait** [comment]
I think you are right!
I would like to avoid warnings within ColorScheme.
