### ISSUE TITLE
Even though it contains multiple elements, the avoid_single_child warning appears when using an if condition.

### ISSUE THREAD

**Issue by yuukiw00w** [altive/altive_lints#68]
**Describe the bug**
Even though it contains multiple elements, the avoid_single_child warning appears when using an if condition.

**To Reproduce**
```dart
Column(      // <- avoid_single_child warnings here
  children: [
    if (isA) ...[
      _buildA1(),
      _buildA2(),
    ] else if (isB) ...[
      _buildB1(),
      _buildB2(),
    ] else ...[
      _buildC1(),
      _buildC2(),
    ],
  ],
)
```

**Expected behavior**
if condition children has not warnings

**Comment by riscait** [comment]
I think you are right!
I would like to avoid the warning if the if-else had more than one content.
